<a href="https://colab.research.google.com/github/abegpatel/churns-modeling-using-ANN/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from keras.models import load_model



In [2]:
seed = 7
np.random.seed(seed)

In [3]:
df=pd.read_csv("/content/Churn_Modelling.csv")
df

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [4]:
df.head()


RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [5]:
df.corr()

RowNumber  CustomerId  ...  EstimatedSalary    Exited
RowNumber         1.000000    0.004202  ...        -0.005988 -0.016571
CustomerId        0.004202    1.000000  ...         0.015271 -0.006248
CreditScore       0.005840    0.005308  ...        -0.001384 -0.027094
Age               0.000783    0.009497  ...        -0.007201  0.285323
Tenure           -0.006495   -0.014883  ...         0.007784 -0.014001
Balance          -0.009067   -0.012419  ...         0.012797  0.118533
NumOfProducts     0.007246    0.016972  ...         0.014204 -0.047820
HasCrCard         0.000599   -0.014025  ...        -0.009933 -0.007138
IsActiveMember    0.012044    0.001665  ...        -0.011421 -0.156128
EstimatedSalary  -0.005988    0.015271  ...         1.000000  0.012097
Exited           -0.016571   -0.006248  ...         0.012097  1.000000

[11 rows x 11 columns]

In [6]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
X = df.iloc[:, 3:13].values
y = df.iloc[:, 13].values


In [8]:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
ohen = OneHotEncoder(categories='auto')
X =ohen.fit_transform(X).toarray()
X=X[:,1:]

In [9]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [10]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() 
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
#STEP 2 -BUILDING AN ANN

In [12]:
import keras
from keras.layers import Dense
from keras.models import Sequential
#initialize the neural net#bulid layer of neural net#initialize the neural net

In [13]:
#initializing the ann
model=Sequential()
#adding input layer and first hidden layer
model.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))#ip+op/2=avg hidden layer

In [14]:

np.shape(X_train)


(7500, 16934)

In [15]:
np.shape(y_train)

(7500,)

In [16]:
model.add(Dense(6, input_shape=(7500,16934), activation='relu'))

In [17]:
# Adding the second hidden layer
model.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
#ip+op/2=avg hidden layer

In [18]:
# Adding the output layer
model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
#ip+op/2=avg hidden layer#softmax(sigmoid func apply to mor than two categorie)

In [19]:
# Compiling the ANN
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])#optimizer(find best algo)#binary_,categori_

In [20]:
# Fitting the ANN to the Training set
model.fit(X_train, y_train, epochs=30, batch_size=10)

Epoch 1/30
750/750 [==============================] - 2s 2ms/step - loss: 0.5270 - accuracy: 0.7953
Epoch 2/30
750/750 [==============================] - 2s 2ms/step - loss: 0.4545 - accuracy: 0.7963
Epoch 3/30
750/750 [==============================] - 2s 2ms/step - loss: 0.3791 - accuracy: 0.7963
Epoch 4/30
750/750 [==============================] - 2s 2ms/step - loss: 0.3020 - accuracy: 0.8008
Epoch 5/30
750/750 [==============================] - 2s 2ms/step - loss: 0.2560 - accuracy: 0.8571
Epoch 6/30
750/750 [==============================] - 2s 2ms/step - loss: 0.2285 - accuracy: 0.8761
Epoch 7/30
750/750 [==============================] - 2s 2ms/step - loss: 0.2150 - accuracy: 0.8833
Epoch 8/30
750/750 [==============================] - 2s 2ms/step - loss: 0.2060 - accuracy: 0.8899
Epoch 9/30
750/750 [==============================] - 2s 2ms/step - loss: 0.2000 - accuracy: 0.8931
Epoch 10/30
750/750 [==============================] - 2s 2ms/step - loss: 0.1967 - accuracy: 0.8951

In [21]:
#step 3-making the prediction evaluating the model

In [22]:
# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred

array([[2.9692062e-06],
       [3.1146456e-03],
       [6.8786685e-05],
       ...,
       [3.2666452e-05],
       [3.7174430e-11],
       [1.5026220e-06]], dtype=float32)

In [23]:
y_pred=(y_pred>0.5)
y_pred#true if >0.5 the customer  leave the bank else  not leave the bank

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [24]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred) #2000(1967+21=correct 488+21=incorrect)
cm

array([[1960,   31],
       [ 496,   13]])

In [25]:
accuracy=(1+219)*100/2000
accuracy

11.0

In [26]:
np.shape(X_test)

(2500, 16934)

In [27]:
df.head()


RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [28]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
def build_model(optimizer):
    model = Sequential()
    model.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    model.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    model.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    return model




In [ ]:
model = KerasClassifier(build_fn = build_model)
parameters = {'batch_size': [25, 32],
              'epochs': [100, 500],
              'optimizer': ['adam', 'rmsprop']}
grid_search = GridSearchCV(estimator = model,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10)
grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_
print(best)

In [ ]:
#evaluating the ANN#k-fold cross validation
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
def build_model():
    #initializing the ann
    model=Sequential()
    #adding input layer and first hidden layer
    model.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))#ip+op/2=avg hidden layer
    model.add(Dense(6, input_shape=(7500,16934), activation='relu'))
    # Adding the second hidden layer
    model.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    #ip+op/2=avg hidden layer
    # Adding the output layer
    model.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    #ip+op/2=avg hidden layer#softmax(sigmoid func apply to mor than two categorie)
    # Compiling the ANN
    model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])#optimizer(find best algo)#binary_,categori_
    return model
model=KerasClassifier(build_fn=build_model, epochs=50, batch_size=10)
accuracy=cross_val_score(estimator=model,X=X_train,y=y_train,cv=10,n_jobs=-1)


In [ ]:
# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""
new_prediction = model.predict(sc.transform(np.array([[600.00,0,1,40,3,60000,2,1,1, 50000]])))
new_prediction = (new_prediction > 0.5)
print(new_prediction)